### ISSUE TITLE
No .build folder when updating to 0.1.17

### ISSUE THREAD

**Issue by goatsy** [itszero/wdio-browserstack-service#28]
We used version 0.1.17 of wdio-browserstack-service and noticed all our builds broke.

See the stacktrace below.
When downgrading to 0.1.16 all was fine again, and the missing "build" folder was there again. 

`/home/shopuser/workspace/wdio-yode_live_smoke/node_modules/webdriverio/build/lib/cli.js:457
                throw e;
                ^
Error: Couldn't initialise launcher from service "browserstack".
Error: Cannot find module './build/browserstack-launch-service'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/shopuser/workspace/wdio-yode_live_smoke/node_modules/wdio-browserstack-service/launcher.js:1:99)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Launcher.getLauncher (/home/shopuser/workspace/wdio-yode_live_smoke/node_modules/webdriverio/build/lib/launcher.js:815:35)
    at Launcher._callee$ (/home/shopuser/workspace/wdio-yode_live_smoke/node_modules/webdriverio/build/lib/launcher.js:234:49)
    at tryCatch (/home/shopuser/workspace/wdio-yode_live_smoke/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/home/shopuser/workspace/wdio-yode_live_smoke/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/home/shopuser/workspace/wdio-yode_live_smoke/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/home/shopuser/workspace/wdio-yode_live_smoke/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/shopuser/workspace/wdio-yode_live_smoke/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (/home/shopuser/workspace/wdio-yode_live_smoke/node_modules/core-js/library/modules/_export.js:36:28)
    at Launcher.<anonymous> (/home/shopuser/workspace/wdio-yode_live_smoke/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)`

**Comment by itszero** [comment]
My bad. I forgot to build the project before publishing 0.1.17 just earlier. I've published 0.1.18 to fix this. Sorry for the trouble!
